### ISSUE TITLE
Crashing with mod "Neutral Animals 1.1.0"

### ISSUE THREAD

**Issue by Jurklein** [CleverNucleus/DataAttributes#3] opened 2021-11-14 23:59 UTC
Tried Minecraft 1.17.1 with fabric modloader v0.11.7; mods:
- dataattributes-1.0.6
- neutral-animals-1.1.0
- fabric-language-kotlin-1.6.5+kotlin.1.5.31 (required for neutral-animals)
- cloth-config-5.1.40-fabric
- fabric-api-0.42.+1.17

The intent of the aforementioned mod is enabling passive mob "fight back" whenever a player hits one. When a passive mob is about to inflict the attack, the game crashes with the following error:
...
java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage
...

Full log:
[dataattributes+neutralanimals_crash.log](https://github.com/CleverNucleus/DataAttributes/files/7534992/dataattributes%2Bneutralanimals_crash.log)

**Comment by CleverNucleus** [comment] 2021-11-15 08:27
Hi there,
I've checked this out and I think I've found where the problem is - it's more or less an issue of conflicting mixins inside LivingEntity (I think). I'll look into confirming that this is indeed the issue, if it is then it's easily fixed on the side of Neutral-Animals with roughly 2-3 lines of code.
Thank you for reporting the issue.

**Comment by Jurklein** [comment] 2022-01-05 04:56
Hi @CleverNucleus,

Any update on this?

**Comment by CleverNucleus** [comment] 2022-01-05 12:05
Hi there,
I've not forgotten about this; I plan to submit a merge to fix the [issue](https://github.com/SmushyTaco/Neutral-Animals/issues/2) this month, I've just been a bit busy. I appreciate your continued patience on this issue.
Thanks.

**Comment by CleverNucleus** [comment] 2022-01-10 12:42
Fixed with the latest release of Neutral Animals.

**Closed by CleverNucleus** 2022-01-10 12:42 UTC
